# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_value', models.IntegerField(null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_assistant.Attraction')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=36)),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateField(verbose_name='departure date')),
                ('return_date', models.DateField(verbose_name='return date')),
                ('days', models.IntegerField(default=1)),
                ('destination', models.CharField(max_length=256)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_assistant.Traveler')),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_assistant.Trip'),
        ),
    ]
