# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination',
            new_name='city',
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='state',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
